In [1]:
import torch

In [2]:
arr = torch.randn(3, 5)

In [4]:
# split dim=1
result = torch.unbind(arr, dim=1)

In [5]:
type(result)

tuple

In [6]:
len(result)

5

In [7]:
result

(tensor([ 0.5943, -0.4967, -1.1076]),
 tensor([-0.3934, -0.0590,  0.4159]),
 tensor([ 0.2013, -0.1256,  1.4520]),
 tensor([ 1.6134, -1.3054, -1.4324]),
 tensor([ 0.1969, -1.0013, -0.2997]))

In [8]:
# torch.stack: concatenates a seq of tensors along a new dim

new_arr = torch.stack(result, dim=0)

In [9]:
new_arr.shape == (5, 3)

True

In [10]:
new_arr.shape

torch.Size([5, 3])

In [11]:
new_arr = torch.stack(result, dim=1)

In [12]:
new_arr.shape == (3, 5)

True

In [13]:
torch.stack(result, dim=2).shape

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [15]:
arr = torch.randn(3, 5, 6).unbind(-1)

In [16]:
len(arr)

6

In [17]:
torch.stack(arr, dim=0).shape

torch.Size([6, 3, 5])

In [19]:
# if concatenates on the existing dim, all dims later on will be pushed later on.
torch.stack(arr, dim=1).shape

torch.Size([3, 6, 5])